"""empty message

Revision ID: d9f37ccbf458
Revises: None
Create Date: 2018-09-29 23:27:33.655965

"""

# revision identifiers, used by Alembic.
revision = 'd9f37ccbf458'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Sentiment', sa.Column('spend_time', sa.String(length=80), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Sentiment', 'spend_time')
    ### end Alembic commands ###
